version: "3"

services:
  postgres2:
    image: "postgres:11.1"
    volumes:
      - postgres2:/var/lib/postgresql/data

  app:
    depends_on:
      - "postgres2"
    build: .
    command: bash start.sh
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/team3
      - gems:/gems


volumes:
  postgres2:
  gems:
